### PR TITLE
Correct typo in README.md

### PR DESCRIPTION
**Pull request by AlthafHussainK**
README.md : Correct typo in README.md

Closes https://github.com/AMU-OSS/meta/issues/1

### CODE REVIEW

**Comment by RJ722** [comment]
Can you edit the PR message to say: `Closes #1 `, please?

If you also want to change the commit message also, run the following commands:
```
git checkout master
git commit --amend # This shall open up the commit message in a text editor, Edit the message body 
# to include Closes: #1
git push origin master --force
```
and you\re done! :+1:

**Comment by RJ722** [comment]
Also, a better commit message would be: `Correct typo in README.md`

**Review by RJ722 — CHANGES_REQUESTED** [review]
Also, a better commit message would be: `Correct typo in README.md`

Please refer http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html It's a really awesome document.

**Comment by AlthafHussainK** [comment]
@RJ722 The article you have mentioned is really helpful. Thanks. :heart: 
I've tried to improve commit message. :smile:

**Pull request merged**
